package com.hackx.ruraledtech.p2p.transfer

import android.net.Uri
import android.util.Log
import com.google.common.truth.Truth.assertThat
import com.hackx.ruraledtech.p2p.connection.P2PConnectionManager
import com.hackx.ruraledtech.p2p.storage.PackageStorageManager
import io.mockk.coEvery
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkStatic
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.TestScope
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.runTest
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.security.MessageDigest

@OptIn(ExperimentalCoroutinesApi::class)
class TransferManagerTest {

    @get:Rule
    val tempFolder = TemporaryFolder()

    private val connectionManager: P2PConnectionManager = mockk(relaxed = true)
    private val legacyInstaller: com.hackx.ruraledtech.p2p.integration.ContentInstaller = mockk(relaxed = true)
    private lateinit var packageStorageManager: PackageStorageManager
    private val testDispatcher = UnconfinedTestDispatcher()
    private val testScope = TestScope(testDispatcher)

    private lateinit var transferManager: TransferManager

    @Before
    fun setUp() {
        mockkStatic(Log::class)
        every { Log.d(any<String>(), any<String>()) } returns 0
        every { Log.e(any<String>(), any<String>()) } returns 0
        every { Log.w(any<String>(), any<String>()) } returns 0
        every { Log.e(any<String>(), any<String>(), any<Throwable>()) } returns 0

        mockkStatic(Uri::class)
        every { Uri.fromFile(any()) } returns mockk()

        val storageDir = tempFolder.newFolder("p2p_storage")
        packageStorageManager = PackageStorageManager(storageDir)
        transferManager = TransferManager(
            connectionManager = connectionManager,
            legacyContentInstaller = legacyInstaller,
            packageStorageManager = packageStorageManager,
            ioDispatcher = testDispatcher,
            coroutineScope = testScope
        )
    }

    @Test
    fun `inbound transfer registers offer, maps payloadId, verifies hash and installs successfully`() = runTest {
        val tempPackageFile = tempFolder.newFile("temp_incoming.zip")
        java.util.zip.ZipOutputStream(java.io.FileOutputStream(tempPackageFile)).use { zos ->
            zos.putNextEntry(java.util.zip.ZipEntry("manifest.json"))
            zos.write("{}".toByteArray())
            zos.closeEntry()
        }
        val expectedHash = computeFileHash(tempPackageFile)

        coEvery { legacyInstaller.install(any()) } returns true

        // 1. Register inbound transfer for OFFER
        val transferId = "tx_1001"
        transferManager.registerInboundTransfer(
            transferId = transferId,
            packageId = "pkg_fractions",
            version = 1,
            expectedHash = expectedHash,
            sizeBytes = tempPackageFile.length(),
            endpointId = "peer_node_A"
        )

        // 2. Map payloadId generated by Nearby Connections
        val payloadId = 998877L
        transferManager.associatePayloadId("peer_node_A", payloadId, transferId)

        // 3. Complete file transfer
        var successCallbackFired = false
        transferManager.onFileTransferComplete("peer_node_A", payloadId, tempPackageFile) { pkgId, version, hash ->
            successCallbackFired = true
            assertThat(pkgId).isEqualTo("pkg_fractions")
            assertThat(version).isEqualTo(1)
            assertThat(hash).isEqualTo(expectedHash)
        }
        testScheduler.advanceUntilIdle()

        assertThat(successCallbackFired).isTrue()

        // 4. Verify store-and-forward persistence
        val storedFile = packageStorageManager.getPackageZipFile("pkg_fractions")
        assertThat(storedFile).isNotNull()
    }

    @Test
    fun `corrupted file fails SHA-256 hash verification, deletes temp file, and rejects installation`() = runTest {
        val validContent = "Original Clean Content"
        val expectedHash = computeHash(validContent)
        
        val tamperedFile = tempFolder.newFile("tampered.pkg")
        tamperedFile.writeText("Corrupted or Tampered Data!") // Mismatched hash

        coEvery { legacyInstaller.install(any()) } returns true

        val transferId = "tx_1002"
        transferManager.registerInboundTransfer(
            transferId = transferId,
            packageId = "pkg_tampered",
            version = 1,
            expectedHash = expectedHash,
            sizeBytes = tamperedFile.length(),
            endpointId = "peer_node_B"
        )

        val payloadId = 554433L
        transferManager.associatePayloadId("peer_node_B", payloadId, transferId)

        var successCallbackFired = false
        transferManager.onFileTransferComplete("peer_node_B", payloadId, tamperedFile) { _, _, _ ->
            successCallbackFired = true
        }
        testScheduler.advanceUntilIdle()

        // Must fail verification and not trigger success callback
        assertThat(successCallbackFired).isFalse()

        // Tampered file must be deleted for security
        assertThat(tamperedFile.exists()).isFalse()

        // Store-and-forward storage must not contain the tampered package
        val storedFile = packageStorageManager.getPackageZipFile("pkg_tampered")
        assertThat(storedFile).isNull()
    }

    @Test
    fun `outbound transfer registers transfer and correlates sendFile payloadId`() {
        val dummyUri = mockk<Uri>()
        every { connectionManager.sendFile("peer_node_C", dummyUri) } returns 12345L

        val transferId = "tx_1003"
        transferManager.registerOutboundTransfer(
            transferId = transferId,
            packageId = "pkg_outbound",
            version = 2,
            expectedHash = "hash123",
            sizeBytes = 1000L,
            fileUri = dummyUri,
            endpointId = "peer_node_C"
        )

        val payloadId = transferManager.startOutboundTransfer(transferId)

        assertThat(payloadId).isEqualTo(12345L)
        val transfer = transferManager.getTransferByPayloadId(12345L)
        assertThat(transfer).isNotNull()
        assertThat(transfer?.transferId).isEqualTo(transferId)
        assertThat(transfer?.packageId).isEqualTo("pkg_outbound")
    }

    private fun computeHash(text: String): String {
        val digest = MessageDigest.getInstance("SHA-256")
        val hashBytes = digest.digest(text.toByteArray())
        return hashBytes.joinToString("") { "%02x".format(it) }
    }

    private fun computeFileHash(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        val hashBytes = digest.digest(file.readBytes())
        return hashBytes.joinToString("") { "%02x".format(it) }
    }
}
